Use apt-get source on Ubuntu to get kernel sources.
This abstracts away things like trusty kernels running on precise images.

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -402,16 +402,22 @@ else
 		pkgname="linux-source-${pkgver}_all"
 
 		cd $TEMPDIR
-		echo "Downloading the kernel source for $ARCHVERSION"
-		# Download source deb pkg
-		(wget "$url/${pkgname}.deb" 2>&1) >> "$LOGFILE" || die "wget: Could not fetch $url/${pkgname}.deb"
-		# Unpack
-		echo "Unpacking kernel source"
-		dpkg -x ${pkgname}.deb $TEMPDIR >> "$LOGFILE" || die "dpkg: Could not extract ${pkgname}.deb"
-		# extract and move to SRCDIR
-		tar $taroptions usr/src/linux-source-$KVER.tar.${extension} >> "$LOGFILE" || die "tar: Failed to extract kernel source package"
-		clean_cache
-		mv linux-source-$KVER "$SRCDIR" || die
+		if [[ $DISTRO = ubuntu ]]; then
+			apt-get source linux-image-${ARCHVERSION}
+			clean_cache
+			mv linux-*-$KVER "$SRCDIR" || die
+		else
+			echo "Downloading the kernel source for $ARCHVERSION"
+			# Download source deb pkg
+			(wget "$url/${pkgname}.deb" 2>&1) >> "$LOGFILE" || die "wget: Could not fetch $url/${pkgname}.deb"
+			# Unpack
+			echo "Unpacking kernel source"
+			dpkg -x ${pkgname}.deb $TEMPDIR >> "$LOGFILE" || die "dpkg: Could not extract ${pkgname}.deb"
+			# extract and move to SRCDIR
+			tar $taroptions usr/src/linux-source-$KVER.tar.${extension} >> "$LOGFILE" || die "tar: Failed to extract kernel source package"
+			clean_cache
+			mv linux-source-$KVER "$SRCDIR" || die
+		fi
 		cp "/boot/config-${ARCHVERSION}" "$OBJDIR/.config" || die
 		if [[ "$ARCHVERSION" == *-* ]]; then
 			echo "-${ARCHVERSION#*-}" > "$SRCDIR/localversion" || die
